language: node_js
os: ubuntu
node_js:
  - 18.17.0
cache: pnpm

install:
  - pnpm install

script:
  - pnpm test
  - pnpm build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
